package edu.heuet.shaohua.dataobject;

import java.util.Date;

public class UsersizeDO {

    private Integer id;


    private Integer userId;


    private Double height;

    private Double chest;

    private Double butto;

    private Double waist;

    private Double crotch;

    private Double shoulder;


    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_size.user_id
     *
     * @return the value of user_size.user_id
     *
     * @mbg.generated Fri Aug 27 14:38:24 CST 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_size.user_id
     *
     * @param userId the value for user_size.user_id
     *
     * @mbg.generated Fri Aug 27 14:38:24 CST 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_size.height
     *
     * @return the value of user_size.height
     *
     * @mbg.generated Fri Aug 27 14:38:24 CST 2021
     */
    public Double getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_size.height
     *
     * @param height the value for user_size.height
     *
     * @mbg.generated Fri Aug 27 14:38:24 CST 2021
     */
    public void setHeight(Double height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_size.chest
     *
     * @return the value of user_size.chest
     *
     * @mbg.generated Fri Aug 27 14:38:24 CST 2021
     */
    public Double getChest() {
        return chest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_size.chest
     *
     * @param chest the value for user_size.chest
     *
     * @mbg.generated Fri Aug 27 14:38:24 CST 2021
     */
    public void setChest(Double chest) {
        this.chest = chest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_size.butto
     *
     * @return the value of user_size.butto
     *
     * @mbg.generated Fri Aug 27 14:38:24 CST 2021
     */
    public Double getButto() {
        return butto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_size.butto
     *
     * @param butto the value for user_size.butto
     *
     * @mbg.generated Fri Aug 27 14:38:24 CST 2021
     */
    public void setButto(Double butto) {
        this.butto = butto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_size.waist
     *
     * @return the value of user_size.waist
     *
     * @mbg.generated Fri Aug 27 14:38:24 CST 2021
     */
    public Double getWaist() {
        return waist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_size.waist
     *
     * @param waist the value for user_size.waist
     *
     * @mbg.generated Fri Aug 27 14:38:24 CST 2021
     */
    public void setWaist(Double waist) {
        this.waist = waist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_size.crotch
     *
     * @return the value of user_size.crotch
     *
     * @mbg.generated Fri Aug 27 14:38:24 CST 2021
     */
    public Double getCrotch() {
        return crotch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_size.crotch
     *
     * @param crotch the value for user_size.crotch
     *
     * @mbg.generated Fri Aug 27 14:38:24 CST 2021
     */
    public void setCrotch(Double crotch) {
        this.crotch = crotch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_size.shoulder
     *
     * @return the value of user_size.shoulder
     *
     * @mbg.generated Fri Aug 27 14:38:24 CST 2021
     */
    public Double getShoulder() {
        return shoulder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_size.shoulder
     *
     * @param shoulder the value for user_size.shoulder
     *
     * @mbg.generated Fri Aug 27 14:38:24 CST 2021
     */
    public void setShoulder(Double shoulder) {
        this.shoulder = shoulder;
    }
}