package edu.heuet.shaohua.dao;

import edu.heuet.shaohua.dataobject.UsersizeDO;
import org.springframework.stereotype.Repository;

@Repository
public interface UsersizeDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_size
     *
     * @mbg.generated Fri Aug 27 14:38:24 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_size
     *
     * @mbg.generated Fri Aug 27 14:38:24 CST 2021
     */
    int insert(UsersizeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_size
     *
     * @mbg.generated Fri Aug 27 14:38:24 CST 2021
     */
    int insertSelective(UsersizeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_size
     *
     * @mbg.generated Fri Aug 27 14:38:24 CST 2021
     */
    UsersizeDO selectByPrimaryKey(Integer id);
    UsersizeDO selectByUserId(Integer UserId);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_size
     *
     * @mbg.generated Fri Aug 27 14:38:24 CST 2021
     */
    int updateByPrimaryKeySelective(UsersizeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_size
     *
     * @mbg.generated Fri Aug 27 14:38:24 CST 2021
     */
    int updateByPrimaryKey(UsersizeDO record);
}